DATASETS:
  TRAIN: ("conic_train",)
  TEST: ("conic_val",)
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.001
  STEPS: (60000, 80000)
  MAX_ITER: 90000
INPUT:
  NUM_CLASSES: 7
  DATASET_MAPPER_NAME: "single_class_nuclei"
DATALOADER:
  NUM_WORKERS: 4
TEST:
  DETECTIONS_PER_IMAGE: 256
VERSION: 2
